### ISSUE TITLE
关于一篇论文的疑问

### ISSUE THREAD

**Issue by chenhaishun** [Iven-Wang/DocRE-reading-list#1]
同学你好，在这篇论文中有些许疑惑，想请教一下：
在“Entity Structure Within and Throughout: Modeling Mention Dependencies for Document-Level Relation Extraction“论文中，
论文的主要创新点在于formulate了一个可以反映文档结构的entity-centric adjacency matrix, 在2.3小节也提到"我们利用特定的参数实例化了此矩阵中的元素"，并在之后介绍了两种Transformation module。我想知道在此处是如何将adjacency matrix中的元素实例化为具有特定意义的神经层参数的呢？这个实例化过后的矩阵的信息是否包含在公式（6）中的A或公式（7）中的K，Q呢？是否在此过程中结构信息是否有所损失呢？

期待你的回复！

**Comment by Iven-Wang** [comment]
你好~抱歉刚刚看到
https://ivenwang.com/2021/02/24/ssan/#comment-740
